### ISSUE TITLE
ElmahIoLoggerProvider.IsEnabled always false

### ISSUE THREAD

**Issue by IGx89** [elmahio/Elmah.Io.Extensions.Logging#7]
Was just reading through your code to learn more about creating custom providers for Microsoft.Extensions.Logging and noticed a potential bug in your code. It appears that ElmahIoLoggerProvider.IsEnabled is always false -- its setter is private and it's never set to true. That causes the message queue to never be disposed.

**Comment by ThomasArdal** [comment]
I think you're right. `IsEnabled` is a leftover from an old implementation. It's currently not possible to disable the elmah.io logger for MEL from code. I will come up with a fix.

Thank you so much for reaching out. Really appreciate it 👍

**Comment by IGx89** [comment]
Happy to have been able to help!

**Comment by ThomasArdal** [comment]
Fixed in [3.6.56-pre](https://www.nuget.org/packages/Elmah.Io.Extensions.Logging/3.6.56-pre) 🎉
